HEATMAP_PAD_VALUE = -1
CONFIGS_PADDING_VALUE = -3
STD_PADDING_VALUE = 0

# CARLA settings
IMAGE_H, IMAGE_W = 720, 1280
NUM_TICKS = 3
SLEEP_TIME = 0.1
MINIMAL_PEDESTRIAN_DISTANCE = 0.5
RELOAD_WORLD_FREQ = 800
